# Acknowledgments {#sec-apx-acknowledgments}

## Authors

The following individuals have contributed to developing the contents of this book (in alphabetical order):

- Peiying Cai, University of Zurich, Zurich, Switzerland
- [Leonardo Collado-Torres](https://lcolladotor.github.io/), Lieber Institute for Brain Development, Baltimore, United States
- [Helena L. Crowell](https://helenalc.github.io/), National Center for Genomic Analysis, Barcelona, Spain
- [Estella Yixing Dong](https://estellad.github.io/online-cv/), CHUV and University of Lausanne, Lausanne, Switzerland
- [Martin Emons](https://github.com/mjemons), University of Zurich, Zurich, Switzerland
- [Shila Ghazanfar](https://shazanfar.github.io/), University of Sydney, Sydney, Australia
- [Samuel Gunz](https://github.com/sgunz), University of Zurich, Zurich, Switzerland
- [Boyi Guo](https://boyi-guo.com/), Johns Hopkins University, Baltimore, United States
- [Stephanie C. Hicks](https://www.stephaniehicks.com/), Johns Hopkins University, Baltimore, United States
- [Artür Manukyan](https://artur-man.github.io/), Max Delbrück Center for Molecular Medicine, Berlin, Germany
- Dario Righelli, University of Naples Federico II, Italy
- [Keri Martinowich](https://neuroscience.jhu.edu/research/faculty/56), Lieber Institute for Brain Development, Baltimore, United States
- [Kristen Maynard](https://neuroscience.jhu.edu/research/faculty/166), Lieber Institute for Brain Development, Baltimore, United States
- Pratibha Panwar, University of Sydney, Sydney, Australia
- [Davide Risso](https://drisso.github.io/), University of Padova, Italy
- [Mark D. Robinson](https://robinsonlabuzh.github.io/), University of Zurich, Zurich, Switzerland
- Jieran Sun, CHUV and University of Lausanne, Lausanne, Switzerland
- [Michael Totty](https://github.com/MicTott), Johns Hopkins University, Baltimore, United States
- [Lukas M. Weber](https://lmweber.org/), Boston University, Boston, United States


## Feedback and contributions

Feedback and suggestions may be provided as [GitHub](https://github.com/lmweber/OSTA) issues for discussion with the maintainers.


## Visium data preprocessing

Details on data preprocessing procedures for 10x Genomics Visium data can be found in our related online book [Visium data preprocessing](https://lmweber.org/Visium-data-preprocessing/).


## Additional acknowledgments

- This book is inspired by the [Orchestrating Single-Cell Analysis with Bioconductor (OSCA)](https://bioconductor.org/books/release/OSCA/) book [@Amezquita2020] on analysis workflows for single-cell data using R and Bioconductor.

- We are grateful to the [Bioconductor](https://bioconductor.org/) community and the [Bioconductor Core Team](https://www.bioconductor.org/about/core-team/).


## BiocBook

This book is built using the [BiocBook](https://github.com/js2264/BiocBook) package, developed by [Jacques Serizay](https://jserizay.com/) for building Quarto books with Bioconductor. More details on BiocBook can be found in the [BiocBook book](https://jserizay.com/BiocBookDemo/devel/).


## References {.unnumbered}